// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPoaLCVRUO5V0YRG53Ft5q6hbF8Qd2oA',
    appId: '1:821089791178:web:950e330b3678ce98dd1833',
    messagingSenderId: '821089791178',
    projectId: 'social-13754',
    authDomain: 'social-13754.firebaseapp.com',
    storageBucket: 'social-13754.appspot.com',
    measurementId: 'G-660JL32ELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0UAvbVb1sGr5QWFxq85rx4YF1CzoAWQ',
    appId: '1:821089791178:android:31b7a375155a390cdd1833',
    messagingSenderId: '821089791178',
    projectId: 'social-13754',
    storageBucket: 'social-13754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByxUopGsbg8wftsfVcOrDRehAaNL-KGuc',
    appId: '1:821089791178:ios:a49b5ef44bf9f70fdd1833',
    messagingSenderId: '821089791178',
    projectId: 'social-13754',
    storageBucket: 'social-13754.appspot.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByxUopGsbg8wftsfVcOrDRehAaNL-KGuc',
    appId: '1:821089791178:ios:cca5f945117ddeb2dd1833',
    messagingSenderId: '821089791178',
    projectId: 'social-13754',
    storageBucket: 'social-13754.appspot.com',
    iosBundleId: 'com.example.tiktok.RunnerTests',
  );
}
